BCBS_Api/Controllers/SalesReportController.cs
using BCBS_Api.DataAccess;
using Kendo.Mvc.UI;
using System.Collections.Generic;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using iTextSharp.text;
using System.IO;
using System.Configuration;
using System;
using MvcRazorToPdf;
using iTextSharp.text.pdf;
using BCBS_Api.Models;
using BCBS_Api.Common;

namespace BCBS_Api.Controllers
{
    public class SalesReportController : Controller
    {
        //
        // GET: /Assessment/

        public ActionResult Index()
        {
            try
            {

                if (Session["LoginUserId"] != null)
                {
                    Util.LogInfo("Sales Index", "SalesReport Controller");
                    return View();
                }
                else
                {
                    Session["LoginUserId"] = null;
                    Session.Abandon();
                    Util.LogInfo("Sales Index", "Session Abandon");
                }
            }
            catch (Exception ex)
            {

                string DetailsMessageError = null;
                if (ex.InnerException != null)
                {
                    DetailsMessageError = ex.InnerException.Message + " " + ex.StackTrace;
                }
                else
                {
                    DetailsMessageError = ex.StackTrace;
                }
                Util.LoggError(new System.Diagnostics.StackFrame(0).GetMethod().Name, ex.Message, DetailsMessageError);
            }

            return RedirectToAction("Login", "Account");
        }


        #region Sales
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult GetSalesData([DataSourceRequest] DataSourceRequest request)
        {
            List<SalesCertificate> SalesCertificateModelList = null;

            SalesCertificateModelList = BCBSDataAccess.GetDataForSales();
            if (SalesCertificateModelList == null)
            {
                return Json(new List<SalesCertificate>(), JsonRequestBehavior.AllowGet);
            }
            return Json(SalesCertificateModelList.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        public ActionResult SalesExportData()
        {
            MemoryStream memoryStream = null;
            List<SalesCertificate> SalessModelList = null;
            const string header = "Workday ID, Learner Name,Completion Status,Report Date,Pre-Assm Result,Pre-Assm Score %, Post-Assm Attempt,Post-Assm Result,Post-Assm Score %,Pre-Q01, Pre-Q02, Pre-Q03, Pre-Q04, Pre-Q05, Pre-Q06, Pre-Q07, Pre-Q08, Pre-Q09, Pre-Q10, Pre-Q11, Pre-Q12, Pre-Q13, Pre-Q14, Pre-Q15, Pre-Q16, Pre-Q17, Pre-Q18, Pre-Q19, Pre-Q20, Pre-Q21, Pre-Q22, Pre-Q23, Pre-Q24, Pre-Q25, Post-Q01, Post-Q02, Post-Q03, Post-Q04, Post-Q05, Post-Q06, Post-Q07, Post-Q08, Post-Q09, Post-Q10, Post-Q11, Post-Q12, Post-Q13, Post-Q14, Post-Q15, Post-Q16, Post-Q17, Post-Q18, Post-Q19, Post-Q20, Post-Q21, Post-Q22, Post-Q23, Post-Q24, Post-Q25";
            const string format = "{0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11},{12},{13},{14},{15},{16},{17},{18},{19},{20},{21},{22},{23},{24},{25},{26},{27},{28},{29},{30},{31},{32},{33},{34},{35},{36},{37},{38},{39},{40},{41},{42},{43},{44},{45},{46},{47},{48},{49},{50},{51},{52},{53},{54},{55},{56},{57},{58}";
            string content = string.Empty;
            SalessModelList = BCBSDataAccess.GetDataForSales();
            memoryStream = new MemoryStream();
            if (SalessModelList != null && SalessModelList.Count > 0)
            {
                TextWriter tw = new StreamWriter(memoryStream);
                tw.WriteLine(header);
                foreach (var item in SalessModelList)
                {
                    item.WorkDayId = !String.IsNullOrEmpty(item.WorkDayId) ? (item.WorkDayId.Contains(",") ? item.WorkDayId.Replace(',', '|') : item.WorkDayId) : string.Empty;
                    item.LearnerName = !String.IsNullOrEmpty(item.LearnerName) ? (item.LearnerName.Contains(",") ? item.LearnerName.Replace(',', '|') : item.LearnerName) : string.Empty;
                    item.CompletionStatusString = !String.IsNullOrEmpty(item.CompletionStatusString) ? (item.CompletionStatusString.Contains(",") ? item.CompletionStatusString.Replace(',', '|') : item.CompletionStatusString) : string.Empty;
                    item.ReportDateString = item.ReportDate.ToString("MM/dd/yyyy");

                    item.PreAssmResultString = !String.IsNullOrEmpty(item.PreAssmResultString) ? (item.PreAssmResultString.Contains(",") ? item.PreAssmResultString.Replace(',', '|') : item.PreAssmResultString) : string.Empty;
                    item.PreAssmScore = item.PreAssmScore;
                    //item.PostAssmAttempt = item.PostAssmAttempt;
                    item.PostAssmResult = item.PostAssmResult;
                    if (item.PostAssmAttempt == 0)
                    {
                        item.PostAssmAttemptString = "NA";
                    }
                    else
                    {
                        item.PostAssmAttemptString = item.PostAssmAttempt.ToString();
                    }
                    if (item.PostAssmAttempt == 0)
                    {
                        item.PostAssmResultString = "NA";
                    }
                    else
                    {
                        item.PostAssmResultString = !String.IsNullOrEmpty(item.PostAssmResultString) ? (item.PostAssmResultString.Contains(",") ? item.PostAssmResultString.Replace(',', '|') : item.PostAssmResultString) : string.Empty;
                    }
                    item.PostAssmScore = item.PostAssmScore;                    
                    item.Pre_Q01 = item.Pre_Q01;
                    item.Pre_Q02 = item.Pre_Q02;
                    item.Pre_Q03 = item.Pre_Q03;
                    item.Pre_Q03 = item.Pre_Q03;
                    item.Pre_Q04 = item.Pre_Q04;
                    item.Pre_Q05 = item.Pre_Q05;
                    item.Pre_Q06 = item.Pre_Q06;
                    item.Pre_Q07 = item.Pre_Q07;
                    item.Pre_Q08 = item.Pre_Q08;
                    item.Pre_Q09 = item.Pre_Q09;
                    item.Pre_Q10 = item.Pre_Q10;
                    item.Pre_Q11 = item.Pre_Q11;
                    item.Pre_Q12 = item.Pre_Q12;
                    item.Pre_Q13 = item.Pre_Q13;
                    item.Pre_Q14 = item.Pre_Q14;
                    item.Pre_Q15 = item.Pre_Q15;
                    item.Pre_Q16 = item.Pre_Q16;
                    item.Pre_Q17 = item.Pre_Q17;
                    item.Pre_Q18 = item.Pre_Q18;
                    item.Pre_Q19 = item.Pre_Q19;
                    item.Pre_Q20 = item.Pre_Q20;
                    item.Pre_Q21 = item.Pre_Q21;
                    item.Pre_Q22 = item.Pre_Q22;
                    item.Pre_Q23 = item.Pre_Q23;
                    item.Pre_Q24 = item.Pre_Q24;
                    item.Pre_Q25 = item.Pre_Q25;
                    item.Post_Q01 = item.Post_Q01;
                    item.Post_Q02 = item.Post_Q02;
                    item.Post_Q03 = item.Post_Q03;
                    item.Post_Q04 = item.Post_Q04;
                    item.Post_Q05 = item.Post_Q05;
                    item.Post_Q06 = item.Post_Q06;
                    item.Post_Q07 = item.Post_Q07;
                    item.Post_Q08 = item.Post_Q08;
                    item.Post_Q09 = item.Post_Q09;
                    item.Post_Q10 = item.Post_Q10;
                    item.Post_Q11 = item.Post_Q11;
                    item.Post_Q12 = item.Post_Q12;
                    item.Post_Q13 = item.Post_Q13;
                    item.Post_Q14 = item.Post_Q14;
                    item.Post_Q15 = item.Post_Q15;
                    item.Post_Q16 = item.Post_Q16;
                    item.Post_Q17 = item.Post_Q17;
                    item.Post_Q18 = item.Post_Q18;
                    item.Post_Q19 = item.Post_Q19;
                    item.Post_Q20 = item.Post_Q20;
                    item.Post_Q21 = item.Post_Q21;
                    item.Post_Q22 = item.Post_Q22;
                    item.Post_Q23 = item.Post_Q23;
                    item.Post_Q24 = item.Post_Q24;
                    item.Post_Q25 = item.Post_Q25;
                    content = string.Format(format, item.WorkDayId, item.LearnerName, item.CompletionStatusString, item.ReportDateString, item.PreAssmResultString, item.PreAssmScore, item.PostAssmAttemptString, item.PostAssmResultString, item.PostAssmScore, item.Pre_Q01, item.Pre_Q02, item.Pre_Q03, item.Pre_Q04, item.Pre_Q05, item.Pre_Q06, item.Pre_Q07, item.Pre_Q08, item.Pre_Q09, item.Pre_Q10, item.Pre_Q11, item.Pre_Q12, item.Pre_Q13, item.Pre_Q14, item.Pre_Q15, item.Pre_Q16, item.Pre_Q17, item.Pre_Q18, item.Pre_Q19, item.Pre_Q20, item.Pre_Q21, item.Pre_Q22, item.Pre_Q23, item.Pre_Q24, item.Pre_Q25, item.Post_Q01, item.Post_Q02, item.Post_Q03, item.Post_Q04, item.Post_Q05, item.Post_Q06, item.Post_Q07, item.Post_Q08, item.Post_Q09, item.Post_Q10, item.Post_Q11, item.Post_Q12, item.Post_Q13, item.Post_Q14, item.Post_Q15, item.Post_Q16, item.Post_Q17, item.Post_Q18, item.Post_Q19, item.Post_Q20, item.Post_Q21, item.Post_Q22, item.Post_Q23, item.Post_Q24, item.Post_Q25);
                    tw.WriteLine(content);
                }
                tw.Flush();
            }

            string contentType = "application/octet-stream";
            byte[] pdfdata = null;
            pdfdata = memoryStream.ToArray();
            var filaName = (ConfigurationManager.AppSettings["ProjectName"]);
            var Datetime = "";
            Datetime = DateTime.Now.ToString("dd_MM_yyyy_T_HH:mm");

            return File(pdfdata, contentType, filaName + "_ExportData_" + Datetime + ".csv");
        }

        #endregion
    }
}

BCBS_Api/Views/SalesReport/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@using Kendo.Mvc.UI

@{

    if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Enterprise")
    {
        <h1 style="clear:both;"> Fall Release 2019 - Enterprise </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "CustomerService")
    {
        <h1 style="clear:both;"> Fall Release 2019 - CSP - Commercial (Member)</h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Claims")
    {
        <h1 style="clear:both;"> Fall Release 2019 - CSP - Senior Market </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Healthcare")
    {
        <h1 style="clear:both;"> Fall Release 2019 - CSP-Commercial (Provider) </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Membership")
    {
        <h1 style="clear:both;"> Fall Release 2019 - Membership </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "StateHealthPlan")
    {
        <h1 style="clear:both;"> Fall Release 2019 - StateHealthPlan</h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Claims1")
    {
        <h1 style="clear:both;"> Fall Release 2019 - Membership – SMA</h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Claims3")
    {
        <h1 style="clear:both;"> Fall Release 2019 - FEP for Service </h1>
    }   
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Healthcare1")
    {
        <h1 style="clear:both;"> Fall Release 2019 - SHP - Healthcare</h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Claims2")
    {
        <h1 style="clear:both;"> Fall Release 2019 - Claims - SMA </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Healthcare2")
    {
        <h1 style="clear:both;"> Fall Release 2019 - FEP - Healthcare</h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Healthcare3")
    {
        <h1 style="clear:both;"> Fall Release 2019 - SMA - Healthcare</h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Healthcare4")
    {
        <h1 style="clear:both;"> Fall Release 2019 - Commercial - Healthcare</h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Healthcare5")
    {
        <h1 style="clear:both;"> Fall Release 2019 - Appeals - Healthcare </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Sales")
    {
        <h1 style="clear:both;"> Fall Release 2019 – ClaimsTraining </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Claims4")
    {
        <h1 style="clear:both;"> FEP Open Season for Claims </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Claims5")
    {
        <h1 style="clear:both;"> Not In Use </h1>
    }
    else if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "Claims6")
    {
        <h1 style="clear:both;"> Not In Use </h1>
    }
    else
    {
        <h1 style="clear:both;">  @System.Configuration.ConfigurationManager.AppSettings["ProjectName"] </h1>
    }

}

@(Html.Kendo().Grid<BCBS_Api.Models.SalesCertificate>().Name("SalesGrid")
        .ToolBar(commands => commands.Template(@<text><a id="btnSalesExport" href="@Url.Action("SalesExportData", "SalesReport")">Export Data In Excel</a></text>))
            .Columns(columns =>
            {
                columns.Bound(p => p.SalesId).Hidden(true);//.ClientTemplate(@"# if (Pre_Assm_Result == true || Post_Assm_Result == true) { #<a href='../Assessment/AssessmentCertificate/?SalesId=#=SalesId#' target='_blank'  class='view-btn' >View Certificate</a> # } #").Width(130).Title("").Filterable(false);
                columns.Bound(p => p.WorkDayId).Width(300).Title("WorkDay Id");
                columns.Bound(p => p.LearnerName).Width(300).Title("Learner Name");
                columns.Bound(p => p.CompletionStatusString).Title("Completion Status").Width(280);
                columns.Bound(p => p.ReportDate).Format("{0:MM/dd/yyyy}").Title("Report Date").Width(180);
                columns.Bound(p => p.PreAssmResult).Hidden(true);
                columns.Bound(p => p.PreAssmResultString).Width(180).Title("Pre-Assm Result");
                columns.Bound(p => p.PreAssmScore).Width(200).Title("Pre-Assm Score %");
                columns.Bound(p => p.PostAssmAttempt).Title("Post-Assm Attempt").Width(280).ClientTemplate("#if(PostAssmAttempt == 1) {#1#} else if(PostAssmAttempt == 2) {#2#}else{#NA#}#");
                columns.Bound(p => p.PostAssmResult).Hidden(true);
                //columns.Bound(p => p.PostAssmResultString).Width(180).Title("Post-Assm Result");
                columns.Bound(p => p.PostAssmResultString).Width(180).Title("Post-Assm Result").Width(280).ClientTemplate("#if(PostAssmAttempt == 0) {#NA#}else{##=PostAssmResultString##}#");
                //columns.Bound(p => p.PostAssmResultString).Width(180).Title("Post-Assm Result").Width(280).ClientTemplate("#if(PostAssmAttempt == 0) {#NA#}else{#\'#=PostAssmResultString#\' #}#");
                columns.Bound(p => p.PostAssmScore).Width(200).Title("Post-Assm Score %");
                columns.Bound(p => p.CompletionStatus).Hidden(true);
                columns.Bound(p => p.Pre_Q01).Title("Pre-Q01").Width(100);
                columns.Bound(p => p.Pre_Q02).Title("Pre-Q02").Width(100);
                columns.Bound(p => p.Pre_Q03).Title("Pre-Q03").Width(100);
                columns.Bound(p => p.Pre_Q04).Title("Pre-Q04").Width(100);
                columns.Bound(p => p.Pre_Q05).Title("Pre-Q05").Width(100);
                columns.Bound(p => p.Pre_Q06).Title("Pre-Q06").Width(100);
                columns.Bound(p => p.Pre_Q07).Title("Pre-Q07").Width(100);
                columns.Bound(p => p.Pre_Q08).Title("Pre-Q08").Width(100);
                columns.Bound(p => p.Pre_Q09).Title("Pre-Q09").Width(100);
                columns.Bound(p => p.Pre_Q10).Title("Pre-Q10").Width(100);
                columns.Bound(p => p.Pre_Q11).Title("Pre-Q11").Width(100);
                columns.Bound(p => p.Pre_Q12).Title("Pre-Q12").Width(100);
                columns.Bound(p => p.Pre_Q13).Title("Pre-Q13").Width(100);
                columns.Bound(p => p.Pre_Q14).Title("Pre-Q14").Width(100);
                columns.Bound(p => p.Pre_Q15).Title("Pre-Q15").Width(100);
                columns.Bound(p => p.Pre_Q16).Title("Pre-Q16").Width(100);
                columns.Bound(p => p.Pre_Q17).Title("Pre-Q17").Width(100);
                columns.Bound(p => p.Pre_Q18).Title("Pre-Q18").Width(100);
                columns.Bound(p => p.Pre_Q19).Title("Pre-Q19").Width(100);
                columns.Bound(p => p.Pre_Q20).Title("Pre-Q20").Width(100);
                columns.Bound(p => p.Pre_Q21).Title("Pre-Q21").Width(100);
                columns.Bound(p => p.Pre_Q22).Title("Pre-Q22").Width(100);
                columns.Bound(p => p.Pre_Q23).Title("Pre-Q23").Width(100);
                columns.Bound(p => p.Pre_Q24).Title("Pre-Q24").Width(100);
                columns.Bound(p => p.Pre_Q25).Title("Pre-Q25").Width(100);
                columns.Bound(p => p.Post_Q01).Title("Post-Q01").Width(100);
                columns.Bound(p => p.Post_Q02).Title("Post-Q02").Width(100);
                columns.Bound(p => p.Post_Q03).Title("Post-Q03").Width(100);
                columns.Bound(p => p.Post_Q04).Title("Post-Q04").Width(100);
                columns.Bound(p => p.Post_Q05).Title("Post-Q05").Width(100);
                columns.Bound(p => p.Post_Q06).Title("Post-Q06").Width(100);
                columns.Bound(p => p.Post_Q07).Title("Post-Q07").Width(100);
                columns.Bound(p => p.Post_Q08).Title("Post-Q08").Width(100);
                columns.Bound(p => p.Post_Q09).Title("Post-Q09").Width(100);
                columns.Bound(p => p.Post_Q10).Title("Post-Q10").Width(100);
                columns.Bound(p => p.Post_Q11).Title("Post-Q11").Width(100);
                columns.Bound(p => p.Post_Q12).Title("Post-Q12").Width(100);
                columns.Bound(p => p.Post_Q13).Title("Post-Q13").Width(100);
                columns.Bound(p => p.Post_Q14).Title("Post-Q14").Width(100);
                columns.Bound(p => p.Post_Q15).Title("Post-Q15").Width(100);
                columns.Bound(p => p.Post_Q16).Title("Post-Q16").Width(100);
                columns.Bound(p => p.Post_Q17).Title("Post-Q17").Width(100);
                columns.Bound(p => p.Post_Q18).Title("Post-Q18").Width(100);
                columns.Bound(p => p.Post_Q19).Title("Post-Q19").Width(100);
                columns.Bound(p => p.Post_Q20).Title("Post-Q20").Width(100);
                columns.Bound(p => p.Post_Q21).Title("Post-Q21").Width(100);
                columns.Bound(p => p.Post_Q22).Title("Post-Q22").Width(100);
                columns.Bound(p => p.Post_Q23).Title("Post-Q23").Width(100);
                columns.Bound(p => p.Post_Q24).Title("Post-Q24").Width(100);
                columns.Bound(p => p.Post_Q25).Title("Post-Q25").Width(100);
            })
            .Pageable(paging => paging.PageSizes(new int[] { 10, 15, 20, 25, 30 }).PreviousNext(true).Refresh(true).Info(true).Input(true).Numeric(true))
            .Scrollable(s => s.Height("auto"))
            .Sortable()
            .Filterable()
            .Resizable(x => x.Columns(true))
            .DataSource(dataSource => dataSource.Ajax()
            .PageSize(10)
            .ServerOperation(false)
            .Model(model =>
            {
                model.Id(p => p.SalesId);
            })
                            .Events(ev => ev.Error("onDataSourceSalesGrid"))
               .Read(read => read.Action("GetSalesData", "SalesReport"))
            )
)
<script type="text/javascript">

    $(document).ready(function () {
        $("#btnSalesExport").button();
    });

    function onDataSourceSalesGrid() {
        alert("Error occoured to fetch record from server.");
    }
</script>