BCBS_Api/Models/SCARFSurveyAnswer.cs
using LINQtoCSV;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BCBS_Api.Models
{
    public class SCARFSurveyAnswerModels
    {
        public int SCARFSurveyId { get; set; }
        public string WorkDayId { get; set; }
        public string LearnerName { get; set; }
        public string managerName { get; set; }
        public string managerEmailID { get; set; }
        public string Status { get; set; }
        public string StatusText { get; set; }
        public string Certainty { get; set; }
        public string CertaintyText { get; set; }
        public string Autonomy { get; set; }
        public string AutonomyText { get; set; }
        public string Relatedness { get; set; }
        public string RelatednessText { get; set; }
        public string Fairness { get; set; }
        public string FairnessText { get; set; }
        public DateTime ReportDate { get; set; }
        public string ReportDateString { get; set; }
        public bool IsErrrorMsg { get; set; }
        public string Message { get; set; }

    }

}

BCBS_Api/Controllers/SCARFSurveyAnswerController.cs
using BCBS_Api.DataAccess;
using Kendo.Mvc.UI;
using System.Collections.Generic;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using iTextSharp.text;
using System.IO;
using System.Configuration;
using System;
using MvcRazorToPdf;
using iTextSharp.text.pdf;
using BCBS_Api.Models;
using BCBS_Api.Common;
using System.Reflection;
using System.Web.Http;
using System.IO;
using System.Data.SqlClient;
using LINQtoCSV;
using System.Collections;
using System.Web;
using System.Web.Routing;



namespace BCBS_Api.Controllers
{
    public class SCARFSurveyAnswerController : Controller
    {
        //
        // GET: /Assessment/

        public ActionResult Index()
        {
            try
            {

                if (Session["LoginUserId"] != null)
                {
                    Util.LogInfo("SCARFSurveyAnswer Index", "SCARFSurveyAnswer Controller");
                    return View();
                }
                else
                {
                    Session["LoginUserId"] = null;
                    Session.Abandon();
                    Util.LogInfo("SCARFSurveyAnswer Index", "Session Abandon");
                }
            }
            catch (Exception ex)
            {

                string DetailsMessageError = null;
                if (ex.InnerException != null)
                {
                    DetailsMessageError = ex.InnerException.Message + " " + ex.StackTrace;
                }
                else
                {
                    DetailsMessageError = ex.StackTrace;
                }
                Util.LoggError(new System.Diagnostics.StackFrame(0).GetMethod().Name, ex.Message, DetailsMessageError);
            }

            return RedirectToAction("Login", "Account");
        }

        #region SCARFSurveyAnswer

        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult GetSCARFSurveyAnswerData([DataSourceRequest] DataSourceRequest request)
        {
            List<SCARFSurveyAnswerModels> SCARFSurveyAnswerModelsList = null;

            SCARFSurveyAnswerModelsList = BCBSDataAccess.GetDataForSCARFSurveyAnswer();
            if (SCARFSurveyAnswerModelsList == null)
            {
                return Json(new List<SCARFSurveyAnswerModels>(), JsonRequestBehavior.AllowGet);
            }
            return Json(SCARFSurveyAnswerModelsList.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetExporttoSCARFSurveyAnswerData()
        {
            MemoryStream memoryStream = null;
            List<SCARFSurveyAnswerModels> SCARFSurveyAnswerModelsList = null;
            const string header = "Workday ID,Learner Name,Manager Name,Manager Email Address,Report Date,Status,Status Text,Certainty,Certainty Text,Autonomy,Autonomy Text,Relatedness,Relatedness Text,Fairness,Fairness Text";
            const string format = "{0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11},{12},{13},{14}";
            string content = string.Empty;
            SCARFSurveyAnswerModelsList = BCBSDataAccess.GetDataForSCARFSurveyAnswer();
            memoryStream = new MemoryStream();
            if (SCARFSurveyAnswerModelsList != null && SCARFSurveyAnswerModelsList.Count > 0)
            {
                TextWriter tw = new StreamWriter(memoryStream);
                tw.WriteLine(header);
                foreach (var item in SCARFSurveyAnswerModelsList)
                {
                    item.WorkDayId = item.WorkDayId;
                    item.LearnerName = item.LearnerName;
                    item.managerName = item.managerName;
                    item.managerEmailID = item.managerEmailID;
                    item.ReportDateString = item.ReportDate.ToString("MM/dd/yyyy").Trim();
                    item.Status = item.Status;
                    item.StatusText = item.StatusText;
                    item.Certainty = item.Certainty;
                    item.CertaintyText = item.CertaintyText;
                    item.Autonomy = item.Autonomy;
                    item.AutonomyText = item.AutonomyText;
                    item.Relatedness = item.Relatedness;
                    item.RelatednessText = item.RelatednessText;
                    item.Fairness = item.Fairness;
                    item.FairnessText = item.FairnessText;
                    content = string.Format(format, item.WorkDayId, item.LearnerName, item.managerName, item.managerEmailID, item.ReportDateString, item.Status, item.StatusText, item.Certainty, item.CertaintyText, item.Autonomy, item.AutonomyText, item.Relatedness, item.RelatednessText, item.Fairness, item.FairnessText);
                    tw.WriteLine(content);
                }
                tw.Flush();
            }

            string contentType = "application/octet-stream";
            byte[] pdfdata = null;
            pdfdata = memoryStream.ToArray();
            var filaName = (ConfigurationManager.AppSettings["ProjectName"]);
            var Datetime = "";
            Datetime = DateTime.Now.ToString("dd_MM_yyyy_T_HH:mm");

            return File(pdfdata, contentType, filaName + "_ExportData_" + Datetime + ".csv");
        }

        #endregion

    }
}

BCBS_Api/Views/SCARFSurveyAnswer/Index.cshtml
@{
    ViewBag.Title = "SCARF Survey";
}
@using Kendo.Mvc.UI

@{
 if (System.Configuration.ConfigurationManager.AppSettings["ProjectName"] == "SCARF Survey")
    {
        <h1 style="clear:both;"> SCARF Survey </h1>
    }   

}

@(Html.Kendo().Grid<BCBS_Api.Models.SCARFSurveyAnswerModels>().Name("SCARFSurveyAnswerGrid")
        .ToolBar(commands => commands.Template(@<text><a id="btnSCARFSurveyAnswerExport" href="@Url.Action("GetExporttoSCARFSurveyAnswerData", "SCARFSurveyAnswer")">Export Data In Excel</a></text>))
            .Columns(columns =>
            {
                columns.Bound(p => p.SCARFSurveyId).Hidden(true);
                columns.Bound(p => p.WorkDayId).Width(300).Title("WorkDay Id");
                columns.Bound(p => p.LearnerName).Width(300).Title("Learner Name");
                columns.Bound(p => p.ReportDate).Format("{0:MM/dd/yyyy}").Title("Report Date").Width(180);
                columns.Bound(p => p.managerName).Title("Manager Name").Width(280);
                columns.Bound(p => p.managerEmailID).Title("Manager Email Address").Width(280);
                columns.Bound(p => p.Status).Width(180).Title("Status");
                columns.Bound(p => p.StatusText).Width(300).Title("Status Text");
                columns.Bound(p => p.Certainty).Width(180).Title("Certainty");
                columns.Bound(p => p.CertaintyText).Width(300).Title("Certainty Text");
                columns.Bound(p => p.Autonomy).Width(180).Title("Autonomy");
                columns.Bound(p => p.AutonomyText).Width(300).Title("Autonomy Text");
                columns.Bound(p => p.Relatedness).Width(180).Title("Relatedness");
                columns.Bound(p => p.RelatednessText).Width(300).Title("Relatedness Text");
                columns.Bound(p => p.Fairness).Width(180).Title("Fairness");
                columns.Bound(p => p.FairnessText).Width(300).Title("Fairness Text");
            })
            .Pageable(paging => paging.PageSizes(new int[] { 1000, 1500, 2000, 2500, 3000 }).PreviousNext(true).Refresh(true).Info(true).Input(true).Numeric(true))
            .Scrollable(s => s.Height("auto"))
            .Sortable()
            .Filterable()
            .Resizable(x => x.Columns(true))
            .DataSource(dataSource => dataSource.Ajax()
            .PageSize(1000)
            .ServerOperation(false)
            .Model(model =>
            {
                model.Id(p => p.SCARFSurveyId);
            })
              .Events(ev => ev.Error("OnDataSCARFSurveyAnswerGrid"))
              .Read(read => read.Action("GetSCARFSurveyAnswerData", "SCARFSurveyAnswer"))
            )
)
<script type="text/javascript">

    $(document).ready(function () {
        $("#btnSCARFSurveyAnswerExport").button();
    });

    function OnDataSCARFSurveyAnswerGrid() {
        alert("Error occoured to fetch record from server.");
    }
</script>

BCBS_Api/Views/SCARFSurveyAnswer/SCARFSurveyAnswerPDF.cshtml
@model BCBS_Api.Models.SCARFSurveyAnswerModels

@{
    Layout = null;
}

<p>Certificate of Completion</p>